#http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#search multipart
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB