server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true
    
# jsp支持
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
# 关闭默认模版引擎
  thymeleaf:
    cache: false
    enabled: false
    
#################redis基础配置#################
  redis:
    database: 0
    host: 192.168.100.101
    password: redis123456
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    
#################redis线程池设置#################
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        #连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 2000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000
        
#################redis哨兵设置#################
    #sentinel:
      # Redis服务器master的名字
    #  master: master8026
      # redis-sentinel的配置地址和端口
    #  nodes:
    #  - 10.189.80.25:26379
    #  - 10.189.80.26:26379
    #  - 10.189.80.27:26378
      